#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
# $1 is The path to the file to be transferred
# $2 is The IP of the server we want to transfer the file to
# $3 is The username scp connects with
# $4 is The path to the SSH private key that scp uses
if [[ $# == 4 ]]
then
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/ 
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
