#!/usr/bin/env bash
# this script:
# 1) Install nginx
# 2) When querying Nginx at its root /
#    with a GET request (requesting a page)
#    using curl, it must return a page that
#    contains the string "Hello World"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
service nginx start
