#!/usr/bin/env bash
# this script:
# 1) Install nginx
# 2) When querying Nginx at its root /
#    with a GET request (requesting a page)
#    using curl, it must return a page that
#    contains the string "Hello World"
# nota: nombres predeterminados de nginx en el dir html:
#       index, index.html, index.htm, index.nginx-debian.html;
# 3) Configure your Nginx server so that
#   "/redirect_me" is redirecting to another page.
# 4) The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sed -i "s/string_to_replace/$new_string/" file
service nginx start
