#!/usr/bin/env bash
# this script: Install and configure HAproxy on your lb-01 server.
# video clave: https://www.youtube.com/watch?v=7ljiOD6MbLA&ab_channel=codigofacilito
sudo apt-get -y update
sudo apt-get -y install haproxy

new_string="frontend http_front\n\t bind *:80\n\t default_backend http_back\n backend http_back\n\t balance roundrobin\n\t server 4739-web-01 3.91.46.188\n\t server 4739-web-02 34.207.144.236"
string_to_replace="errorfile 504 /etc/haproxy/errors/504.http"
sudo sed -i "/$string_to_replace/ a $new_string_1" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
