#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi
contador=9
# -ge es mayor o igual
while [ $contador -ge 0 ]
do
  if [[ "$contador" == '1' ]]
  then
    echo "Hi"
  fi
  echo "Best School"
  ((contador--))
done
